### ISSUE TITLE
X and Y axes don’t align with the grid lines in the graphing space

### ISSUE THREAD

**Issue by Valenciola** [makaip/mathematix#31]
As can be seen in this (beautiful) image here, Mathematix can accurately output functions. However, there’s a little bit of an issue when it comes to the actual lines in the graph: they don’t align with the white axes (x = 0 and y = 0 lines).

![image](https://github.com/makaip/mathematix/assets/93671200/1a3f7f49-e521-4643-8492-ab29d306eb9c)

I’m not too sure, but maybe this can be fixed by just shifting the dark lines over a little bit, rather than shifting the axes (and the origin, which would end up shifting the entire graph location). I’ll have to investigate a little further.

**Comment by Valenciola** [comment]
It seems like taking a look at draw.js (https://github.com/makaip/mathematix/blob/main/grapher/draw.js) is a good place to start; I’ll see about this in the morning.

**Comment by AlexanderJCS** [comment]
draw.js is definitely the culprit here. Don't shift the gray lines over unless you have reason to suspect that those are the inaccurate ones. You can check this guys graphing y=x and seeing if it aligns perfectly (you may need to take a screenshot and zoom in).

It might just be a math error or something, or it doesn't account for the thickness of the line (highly doubt it, since it shouldn't need to do this, but maybe??).
